name: Swift Build, Test & Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: '5.9'

      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint lint --reporter github-actions-logging

      - name: SPM Build
        run: swift build -v

      - name: SPM Test
        run: swift test -v --enable-code-coverage

      - name: Xcode Build
        run: |
          xcodebuild clean build -project "SwiftUi MVVM Template.xcodeproj" \
            -scheme "SwiftUi MVVM Template" \
            -destination "platform=iOS Simulator,name=iPhone 15 Pro" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Xcode Test
        run: |
          xcodebuild test -project "SwiftUi MVVM Template.xcodeproj" \
            -scheme "SwiftUi MVVM Template" \
            -destination "platform=iOS Simulator,name=iPhone 15 Pro" \
            -enableCodeCoverage YES \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          swift: true
          fail_ci_if_error: true
